import React, { useState, useRef } from 'react';
import SnowGlobe, { SnowGlobeHandle } from './components/SnowGlobe';
import { SceneType } from './types';

const App: React.FC = () => {
  const [scene, setScene] = useState<SceneType>('WINTER');
  const [customText, setCustomText] = useState<string>("Magic World");
  const [isRecording, setIsRecording] = useState(false);
  const snowGlobeRef = useRef<SnowGlobeHandle>(null);

  const scenes: { id: SceneType; label: string; icon: string }[] = [
    { id: 'WINTER', label: 'Winter', icon: '❄️' },
    { id: 'RAIN', label: 'Rain', icon: '🌧️' },
    { id: 'FISH', label: 'Ocean', icon: '🐠' },
    { id: 'SAKURA', label: 'Sakura', icon: '🌸' },
    { id: 'CAROUSEL', label: 'Carousel', icon: '🎠' },
    { id: 'SHANGHAI', label: 'Shanghai', icon: '🏙️' },
    { id: 'CAT_MOUSE', label: 'Cat & Mouse', icon: '🐈' },
    { id: 'BIRTHDAY', label: 'Birthday', icon: '🎂' },
  ];

  const handleDownload = async () => {
    if (snowGlobeRef.current && !isRecording) {
      setIsRecording(true);
      try {
        await snowGlobeRef.current.captureVideo();
      } catch (e) {
        console.error("Recording failed", e);
      } finally {
        setIsRecording(false);
      }
    }
  };

  return (
    <div className="w-screen h-screen flex flex-col items-center justify-center bg-gradient-to-b from-slate-900 to-slate-800 text-white overflow-hidden relative">
      
      <div className="z-10 text-center mb-2 pointer-events-none absolute top-4 w-full">
        <h1 className="text-3xl font-serif tracking-widest text-slate-200 drop-shadow-lg opacity-80">
          MAGIC MICROCOSM
        </h1>
        <p className="text-sm text-slate-400 mt-1 font-light">
          Choose a world, write a wish, and keep the memory.
        </p>
      </div>

      <div className="relative z-0 shadow-2xl rounded-full mt-4 group">
        <SnowGlobe ref={snowGlobeRef} currentScene={scene} message={customText} />
      </div>

      {/* Controls Container */}
      <div className="absolute bottom-6 z-20 w-full max-w-4xl px-4 flex flex-col gap-4 items-center">
        
        {/* Base Text Editor & Download */}
        <div className="flex gap-2 items-center bg-slate-900/60 backdrop-blur-md p-2 rounded-xl border border-slate-700/50 shadow-lg">
          <input 
            type="text" 
            value={customText}
            onChange={(e) => setCustomText(e.target.value)}
            maxLength={20}
            className="bg-transparent border-b border-slate-500 text-center text-amber-400 font-serif placeholder-slate-600 focus:outline-none focus:border-amber-400 px-2 py-1 w-48"
            placeholder="Engrave text..."
          />
          <button 
            onClick={handleDownload}
            disabled={isRecording}
            className={`px-4 py-1.5 rounded-lg font-medium text-xs uppercase tracking-wide transition-all ${
              isRecording 
                ? 'bg-red-500/20 text-red-400 cursor-wait animate-pulse' 
                : 'bg-indigo-600 hover:bg-indigo-500 text-white shadow-md'
            }`}
          >
            {isRecording ? 'Recording...' : 'Save Video'}
          </button>
        </div>

        {/* Scene Selector */}
        <div className="flex gap-3 overflow-x-auto pb-2 pt-2 justify-center w-full scrollbar-hide">
          {scenes.map((s) => (
            <button
              key={s.id}
              onClick={() => setScene(s.id)}
              className={`flex-shrink-0 flex flex-col items-center gap-1 px-4 py-3 rounded-xl transition-all duration-300 border backdrop-blur-md ${
                scene === s.id
                  ? 'bg-slate-700/80 border-slate-500 text-white scale-110 shadow-[0_0_15px_rgba(255,255,255,0.2)]'
                  : 'bg-slate-900/40 border-slate-700/30 text-slate-400 hover:text-slate-200 hover:bg-slate-800/60'
              }`}
            >
              <span className="text-2xl filter drop-shadow-md">{s.icon}</span>
              <span className="text-[10px] uppercase tracking-wider font-semibold">{s.label}</span>
            </button>
          ))}
        </div>
      </div>

      <div className="absolute bottom-1 text-slate-600 text-[10px] font-mono pointer-events-none">
        Generated by Gemini
      </div>
    </div>
  );
};

export default App;